#pragma once

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <span>
#include <string_view>
#include <vector>

#include "ninfer/types.h"

namespace ninfer::runtime {

// The marker the output policy splits the reasoning channel on: the first "</think>" in a turn, and
// the same point the history renderer needs for the reasoning it trims.
inline constexpr std::string_view kAssistantThinkClose = "</think>";

// Whether two renderings describe the same assistant turn.
//
// "generated" is the turn as this lineage wrote it: the model's bytes, which carry whatever framing
// whitespace it chose. "replayed" is the client's rendering of the same turn, produced by the chat
// template, which trims the reasoning and the content and writes its own separators around them. The
// template cannot reproduce framing whitespace it does not control, so a client that echoes the
// answer it was handed can differ from the generated bytes in exactly those runs and still describe
// the same turn - and only then may its tokens be replaced by the generated ones, because the KV
// that is reused belongs to the generated bytes.
//
// Everything outside those runs has to match. The tool-call region carries the program the model
// wrote, so a reordered argument object, an added default, an edited line, an extra call or a
// different call name is a different turn and must keep the client's own tokens.
[[nodiscard]] inline bool same_rendered_turn(std::string_view generated, std::string_view replayed) {
    constexpr std::string_view kToolCallOpen  = "<tool_call>";
    constexpr std::string_view kToolCallClose = "</tool_call>";
    const auto is_space = [](char ch) {
        return ch == ' ' || ch == '\t' || ch == '\n' || ch == '\r' || ch == '\f' || ch == '\v';
    };
    const auto trim = [&](std::string_view text) {
        while (!text.empty() && is_space(text.front())) { text.remove_prefix(1); }
        while (!text.empty() && is_space(text.back())) { text.remove_suffix(1); }
        return text;
    };
    const auto split = [](std::string_view text, std::string_view& head, std::string_view& body) {
        const std::size_t close = text.find(kAssistantThinkClose);
        if (close == std::string_view::npos) { return false; }
        head = text.substr(0, close);
        body = text.substr(close + kAssistantThinkClose.size());
        return true;
    };
    std::string_view generated_head;
    std::string_view generated_body;
    std::string_view replayed_head;
    std::string_view replayed_body;
    const bool generated_closed = split(generated, generated_head, generated_body);
    if (!split(replayed, replayed_head, replayed_body)) { return false; }
    if (!generated_closed) {
        // The model's turn was cut off inside its reasoning: it never wrote the close marker, and the
        // template writes one for the reasoning it renders. The whole generated turn is the reasoning
        // then, and the replay may add nothing but that marker and the framing around it. A turn with
        // answer content of its own is a different turn and keeps the client's own tokens.
        return trim(generated) == trim(replayed_head) && trim(replayed_body).empty();
    }
    if (trim(generated_head) != trim(replayed_head)) { return false; }
    const std::size_t generated_open = generated_body.find(kToolCallOpen);
    const std::size_t replayed_open  = replayed_body.find(kToolCallOpen);
    if ((generated_open == std::string_view::npos) != (replayed_open == std::string_view::npos)) {
        return false;
    }
    if (generated_open == std::string_view::npos) {
        return trim(generated_body) == trim(replayed_body);
    }
    if (trim(generated_body.substr(0, generated_open)) !=
        trim(replayed_body.substr(0, replayed_open))) {
        return false;
    }
    // Every call this turn carries, from the first opener through the last closer. The framing
    // between two calls is the template's as well, so it is compared with the calls themselves.
    const std::size_t generated_close = generated_body.rfind(kToolCallClose);
    const std::size_t replayed_close  = replayed_body.rfind(kToolCallClose);
    if (generated_close == std::string_view::npos || replayed_close == std::string_view::npos) {
        return false;
    }
    const std::size_t generated_end = generated_close + kToolCallClose.size();
    const std::size_t replayed_end  = replayed_close + kToolCallClose.size();
    return generated_body.substr(generated_open, generated_end - generated_open) ==
           replayed_body.substr(replayed_open, replayed_end - replayed_open);
}

// One history an incoming prompt could be continuing: the tokens a lineage committed, and where the
// answer it wrote begins inside them.
struct AdoptionSource {
    std::span<const TokenId> history;
    std::size_t turn_begin = 0;
    // This lane's own KV still holds the history, so it is the state the lane really carries and it
    // hides every other source.
    bool resident = false;
    // Host slabs carry the history, so a recall can bring it back onto any lane.
    bool stored = false;
    // Diagnostics: -1 for the lane's own lineage, otherwise the catalog index the history came from.
    std::int64_t id = -1;
};

// A source that can describe the turn a client replayed, with the number of tokens it agrees with
// the incoming prompt on.
struct AdoptionCandidate {
    // Index into the sources the candidate came from.
    std::size_t source = 0;
    std::size_t shared = 0;
};

// The histories an incoming prompt could be continuing, deepest agreement first.
//
// A lane that still holds its own lineage offers only that one: it is the state this lane's KV
// actually carries, which is what a single-lane route has always run. A lane that has retired its
// lineage - the batched route hands its pages back and drops the lineage when a request retires -
// has nothing left but the catalog, and the replayed answer then has to be matched against the
// stored conversations instead. That is the entry a recall is about to restore onto this lane
// anyway, so agreeing with it is exactly what keeps the conversation resident.
//
// "divergence" accumulates the deepest agreement over the sources this call considers - the ones the
// lane's own lineage does not hide and that have KV to restore - because it is the reuse measurement
// a caller reports when nothing is adopted.
[[nodiscard]] inline std::vector<AdoptionCandidate>
adoption_candidates(std::span<const TokenId> incoming, std::span<const AdoptionSource> sources,
                    std::size_t& divergence) {
    bool have_resident = false;
    for (const AdoptionSource& source : sources) {
        if (source.resident) {
            have_resident = true;
            break;
        }
    }
    std::vector<AdoptionCandidate> candidates;
    for (std::size_t index = 0; index < sources.size(); ++index) {
        const AdoptionSource& source = sources[index];
        if (have_resident ? !source.resident : !source.stored) { continue; }
        // The whole history in front of the turn has to match, or this is a different history and not
        // a replay of the answer it wrote. An empty boundary means no completed prefill is in reach.
        if (source.history.empty() || source.turn_begin == 0 ||
            source.history.size() <= source.turn_begin || incoming.size() <= source.turn_begin) {
            continue;
        }
        const std::size_t common = std::min(source.history.size(), incoming.size());
        std::size_t shared       = 0;
        while (shared < common && source.history[shared] == incoming[shared]) { ++shared; }
        divergence = std::max(divergence, shared);
        if (shared < source.turn_begin) { continue; }
        candidates.push_back(AdoptionCandidate{index, shared});
    }
    // Deepest agreement first: that is the conversation this prompt is a later turn of. A history the
    // client agrees with further is never a worse guess than one it parts from sooner.
    std::stable_sort(candidates.begin(), candidates.end(),
                     [&](const AdoptionCandidate& left, const AdoptionCandidate& right) {
                         if (left.shared != right.shared) { return left.shared > right.shared; }
                         return sources[left.source].history.size() >
                                sources[right.source].history.size();
                     });
    return candidates;
}

} // namespace ninfer::runtime
