#pragma once

#include <cstddef>
#include <string_view>

namespace ninfer::runtime {

// The marker the output policy splits the reasoning channel on: the first "</think>" in a turn, and
// the same point the history renderer needs for the reasoning it trims.
inline constexpr std::string_view kAssistantThinkClose = "</think>";

// Whether two renderings describe the same assistant turn.
//
// "generated" is the turn as this lineage wrote it: the model's bytes, which carry whatever framing
// whitespace it chose. "replayed" is the client's rendering of the same turn, produced by the chat
// template, which trims the reasoning and the content and writes its own separators around them. The
// template cannot reproduce framing whitespace it does not control, so a client that echoes the
// answer it was handed can differ from the generated bytes in exactly those runs and still describe
// the same turn - and only then may its tokens be replaced by the generated ones, because the KV
// that is reused belongs to the generated bytes.
//
// Everything outside those runs has to match. The tool-call region carries the program the model
// wrote, so a reordered argument object, an added default, an edited line, an extra call or a
// different call name is a different turn and must keep the client's own tokens.
[[nodiscard]] inline bool same_rendered_turn(std::string_view generated, std::string_view replayed) {
    constexpr std::string_view kToolCallOpen  = "<tool_call>";
    constexpr std::string_view kToolCallClose = "</tool_call>";
    const auto is_space = [](char ch) {
        return ch == ' ' || ch == '\t' || ch == '\n' || ch == '\r' || ch == '\f' || ch == '\v';
    };
    const auto trim = [&](std::string_view text) {
        while (!text.empty() && is_space(text.front())) { text.remove_prefix(1); }
        while (!text.empty() && is_space(text.back())) { text.remove_suffix(1); }
        return text;
    };
    const auto split = [](std::string_view text, std::string_view& head, std::string_view& body) {
        const std::size_t close = text.find(kAssistantThinkClose);
        if (close == std::string_view::npos) { return false; }
        head = text.substr(0, close);
        body = text.substr(close + kAssistantThinkClose.size());
        return true;
    };
    std::string_view generated_head;
    std::string_view generated_body;
    std::string_view replayed_head;
    std::string_view replayed_body;
    const bool generated_closed = split(generated, generated_head, generated_body);
    if (!split(replayed, replayed_head, replayed_body)) { return false; }
    if (!generated_closed) {
        // The model's turn was cut off inside its reasoning: it never wrote the close marker, and the
        // template writes one for the reasoning it renders. The whole generated turn is the reasoning
        // then, and the replay may add nothing but that marker and the framing around it. A turn with
        // answer content of its own is a different turn and keeps the client's own tokens.
        return trim(generated) == trim(replayed_head) && trim(replayed_body).empty();
    }
    if (trim(generated_head) != trim(replayed_head)) { return false; }
    const std::size_t generated_open = generated_body.find(kToolCallOpen);
    const std::size_t replayed_open  = replayed_body.find(kToolCallOpen);
    if ((generated_open == std::string_view::npos) != (replayed_open == std::string_view::npos)) {
        return false;
    }
    if (generated_open == std::string_view::npos) {
        return trim(generated_body) == trim(replayed_body);
    }
    if (trim(generated_body.substr(0, generated_open)) !=
        trim(replayed_body.substr(0, replayed_open))) {
        return false;
    }
    // Every call this turn carries, from the first opener through the last closer. The framing
    // between two calls is the template's as well, so it is compared with the calls themselves.
    const std::size_t generated_close = generated_body.rfind(kToolCallClose);
    const std::size_t replayed_close  = replayed_body.rfind(kToolCallClose);
    if (generated_close == std::string_view::npos || replayed_close == std::string_view::npos) {
        return false;
    }
    const std::size_t generated_end = generated_close + kToolCallClose.size();
    const std::size_t replayed_end  = replayed_close + kToolCallClose.size();
    return generated_body.substr(generated_open, generated_end - generated_open) ==
           replayed_body.substr(replayed_open, replayed_end - replayed_open);
}

} // namespace ninfer::runtime
