// The guard that lets a re-rendered assistant turn be served from the tokens this lineage generated.
//
// It is the only thing standing between a client's replay and the KV that belongs to the answer
// NInfer wrote, so what it must reject is tested as carefully as what it must accept: the template
// trims the reasoning and the content and writes its own separators, which a client echoing the
// answer cannot reproduce byte for byte, but every other difference is a different turn.

#include "runtime/engine/turn_replay.h"

#include <iostream>
#include <string>
#include <string_view>

namespace {

using ninfer::runtime::same_rendered_turn;

int check(bool condition, const char* message) {
    if (condition) { return 0; }
    std::cerr << message << '\n';
    return 1;
}

// One turn as the template renders it: the reasoning, the canonical close, the content, one call.
std::string turn(std::string_view reasoning, std::string_view content, std::string_view call) {
    std::string out(reasoning);
    out += "\n</think>\n\n";
    out += content;
    if (!call.empty()) {
        out += "\n\n<tool_call>\n<function=write>\n<parameter=path>\n";
        out += call;
        out += "\n</parameter>\n<parameter=content>\nconst value = 1;\n</parameter>\n"
               "</function>\n</tool_call>";
    }
    out += "<|im_end|>\n";
    return out;
}

} // namespace

int main() {
    int failures = 0;
    const std::string canonical = turn("I will write the file.", "Here it is:", "app.js");

    // A replay the renderer reproduces exactly.
    failures += check(same_rendered_turn(canonical, canonical),
                      "an identical replay was rejected");

    // The generated bytes carry the model's own framing: an extra newline before the close and a
    // single one after it, where the template writes two. Same turn, so the tokens this lineage
    // generated may be reused.
    std::string generated = turn("I will write the file.", "Here it is:", "app.js");
    const std::size_t close_at = generated.find("\n</think>");
    generated.replace(close_at, std::string_view("\n</think>").size(), "\n\n</think>");
    const std::size_t after_close = generated.find("</think>") + std::string_view("</think>").size();
    generated.erase(after_close, generated.find_first_not_of('\n', after_close) - after_close);
    generated.insert(after_close, "\n");
    failures += check(same_rendered_turn(generated, canonical),
                      "framing whitespace around the close was treated as a different turn");
    failures += check(same_rendered_turn(canonical, generated),
                      "the comparison is not symmetric in the framing runs");

    // The content differs by one character: a different turn.
    const std::string other_content = turn("I will write the file.", "Here it is!", "app.js");
    failures += check(!same_rendered_turn(generated, other_content),
                      "an edited content byte was accepted as the same turn");

    // Whitespace inside the content is content, not framing.
    const std::string inner_space = turn("I will write the file.", "Here  it is:", "app.js");
    failures += check(!same_rendered_turn(generated, inner_space),
                      "interior content whitespace was treated as framing");

    // A reordered argument object, an edited value, or a different path is a different turn: the
    // tool-call region is compared byte for byte.
    const std::string other_call = turn("I will write the file.", "Here it is:", "app.ts");
    failures += check(!same_rendered_turn(generated, other_call),
                      "an edited tool argument was accepted as the same turn");

    // A turn with no call where the generated one had one.
    const std::string no_call = turn("I will write the file.", "Here it is:", "");
    failures += check(!same_rendered_turn(generated, no_call),
                      "a missing tool call was accepted as the same turn");
    failures += check(!same_rendered_turn(no_call, generated),
                      "an extra tool call was accepted as the same turn");

    // Two calls: the second one has to be there as well, and it sits before the turn's end where
    // the template puts it.
    std::string two_calls = turn("I will write the file.", "Here it is:", "app.js");
    two_calls.insert(two_calls.find("<|im_end|>"),
                     "\n\n<tool_call>\n<function=read>\n<parameter=path>\napp.js\n"
                     "</parameter>\n</function>\n</tool_call>");
    failures += check(!same_rendered_turn(generated, two_calls),
                      "a second tool call was ignored by the comparison");

    // A turn the budget stopped inside its reasoning: it never wrote the close marker, and the
    // template writes one for the reasoning it renders. That marker is the template's, so the turn is
    // still the same one - a turn carrying an answer of its own is not.
    const std::string cut_off = "I will write the file.\n";
    failures += check(same_rendered_turn(cut_off, "I will write the file.\n</think>\n\n"),
                      "a cut-off turn with only the template's close was treated as a different turn");
    failures += check(!same_rendered_turn(cut_off, "I will write the file.\n</think>\n\nHere it is."),
                      "a cut-off turn carrying an answer the model never wrote was accepted");
    failures += check(!same_rendered_turn(cut_off, "I will write another file.\n</think>\n\n"),
                      "a cut-off turn with different reasoning was accepted");
    failures += check(!same_rendered_turn(cut_off, canonical),
                      "a cut-off turn whose rendering carries a tool call was accepted");

    // Reasoning differences are differences, framing aside.
    const std::string other_reasoning = turn("I will write another file.", "Here it is:", "app.js");
    failures += check(!same_rendered_turn(generated, other_reasoning),
                      "an edited reasoning byte was accepted as the same turn");

    if (failures == 0) { std::cout << "turn replay guard ok\n"; }
    return failures == 0 ? 0 : 1;
}
