"""Generate Jinja's Unicode 17 full-case exceptions and contextual-case properties.

Input files are SpecialCasing.txt and DerivedCoreProperties.txt from
https://www.unicode.org/Public/17.0.0/ucd/ . Runtime casing otherwise uses bundled utf8proc.
"""

from __future__ import annotations

import argparse
from pathlib import Path


def records(path: Path):
    text = path.read_text(encoding="utf-8")
    if "17.0.0" not in text.splitlines()[0]:
        raise ValueError(f"{path}: expected Unicode 17.0.0")
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            yield [item.strip() for item in line.split(";")]


def cpp_string(sequence: str) -> str:
    data = "".join(chr(int(word, 16)) for word in sequence.split()).encode("utf-8")
    return '"' + "".join(f"\\x{byte:02x}" for byte in data) + '"'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("ucd_directory", type=Path)
    args = parser.parse_args()
    lines = [
        "// Generated by tools/generate_jinja_unicode.py from Unicode 17.0.0 UCD.",
        "// Unicode data license: ../UNICODE-LICENSE. See the generator for source URLs.",
        "#pragma once",
        "#include <cstdint>",
        "#include <string_view>",
        "namespace jinja::unicode::data {",
        "struct Mapping { std::int32_t codepoint; std::string_view lower, title, upper; };",
        "inline constexpr Mapping mappings[] = {",
    ]
    cases = sorted(
        (
            row
            for row in records(args.ucd_directory / "SpecialCasing.txt")
            if not row[4]
        ),
        key=lambda row: int(row[0], 16),
    )
    for row in cases:
        lines.append(
            f"{{0x{row[0]}, {cpp_string(row[1])}, {cpp_string(row[2])}, {cpp_string(row[3])}}},"
        )
    lines += ["};", "struct Range { std::int32_t first, last; };"]
    props = list(records(args.ucd_directory / "DerivedCoreProperties.txt"))
    for prop, name in (("Cased", "cased"), ("Case_Ignorable", "case_ignorable")):
        ranges = []
        for row in props:
            if row[1] == prop:
                bounds = row[0].split("..")
                ranges.append((int(bounds[0], 16), int(bounds[-1], 16)))
        lines.append(f"inline constexpr Range {name}[] = {{")
        for first, last in sorted(ranges):
            lines.append(f"{{0x{first:X}, 0x{last:X}}},")
        lines.append("};")
    lines.append("} // namespace jinja::unicode::data")
    output = (
        Path(__file__).resolve().parents[1]
        / "third_party/llama-jinja/jinja/unicode_data.h"
    )
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
